{ self, inputs, ... }: {
  flake.nixosModules.nushell = { pkgs, lib, ... }: {
    environment.systemPackages = [ self.packages.${pkgs.stdenv.hostPlatform.system}.nushell ];
    environment.shells = [ self.packages.${pkgs.stdenv.hostPlatform.system}.nushell ];

    programs.zsh.interactiveShellInit = ''
      if [[ -o interactive && "$TERM" != "dumb" && -z "$NU_VERSION" ]]; then
        exec ${lib.getExe self.packages.${pkgs.stdenv.hostPlatform.system}.nushell}
      fi
    '';
  };

  perSystem = { pkgs, ... }: let
    # Pre-generate initialization scripts at build time
    zoxide-init = pkgs.runCommand "zoxide.nu" { } "${pkgs.zoxide}/bin/zoxide init nushell > $out";
    carapace-init = pkgs.runCommand "carapace.nu" { } "${pkgs.carapace}/bin/carapace _carapace nushell > $out";
	fzf_style = "--height 40% --layout reverse --border";
  in {
    packages.nushell = inputs.wrapper-modules.wrappers.nushell.wrap {
      inherit pkgs;

      extraPackages = with pkgs; [
        fzf 
		fd 
		starship 
		zoxide 
		direnv 
		sesh 
		carapace
      ];

      env = { KEYTIMEOUT = "20"; };

      "config.nu".content = ''
        # --- 1. CONFIGURATION ---
        $env.config.show_banner = false  # This hides the greeting
        $env.config.edit_mode = "vi"
        $env.config.cursor_shape = {
          vi_insert: "line"
          vi_normal: "block"
        }

        # --- 2. INITIALIZATION (Zoxide & Carapace) ---
        # We source the scripts generated by Nix at build time
        source ${zoxide-init}
        source ${carapace-init}

		# --- carapace ---
		let carapace_completer = {|spans|
          carapace $spans.0 nushell ...$spans | from json
        }

        $env.config.completions.external = {
          enable: true
          max_results: 100
          completer: $carapace_completer
        }

# --- KEYBINDINGS ---
        $env.config.keybindings = (
          $env.config.keybindings | append [
            {
              name: autosuggest_accept
              modifier: control
              keycode: char_h
              mode: [emacs, vi_insert, vi_normal]
              event: { send: HistoryHintComplete }
            }
            {
              name: fzf_history
              modifier: control
              keycode: char_r
              mode: [emacs, vi_insert, vi_normal]
              event: [
                {
                  send: ExecuteHostCommand
                  cmd: "commandline edit --insert (history | get command | reverse | uniq | str join (char nl) | fzf ${fzf_style} --query (commandline) | decode utf-8 | str trim)"
                }
              ]
            }
            {
              name: fzf_files
              modifier: control
              keycode: char_t
              mode: [emacs, vi_insert, vi_normal]
              event: [
                {
                  send: ExecuteHostCommand
                  cmd: "commandline edit --insert (fd --type f --exclude .git | fzf ${fzf_style} | decode utf-8 | str trim)"
                }
              ]
            }
            {
              name: fzf_directories
              modifier: control
              keycode: char_s
              mode: [emacs, vi_insert, vi_normal]
              event: [
                {
                  send: ExecuteHostCommand
                  cmd: "let dest = (fd --type d --exclude .git | fzf ${fzf_style} | decode utf-8 | str trim); if not ($dest | is-empty) { cd $dest }"
                }
              ]
            }
          ]
        )

        # --- 3. ALIASES ---
		alias cd = z
		alias fg = job unfreeze
        alias v = nvim
        alias l = ls
        alias la = ls -l
        alias ts = tmux new -s

        # --- 4. PROMPT (Starship) ---
        $env.STARSHIP_SHELL = "nu"
        def create_left_prompt [] {
          starship prompt --cmd-duration $env.CMD_DURATION_MS $'--status=($env.LAST_EXIT_CODE)'
        }
        $env.PROMPT_COMMAND = { || create_left_prompt }
        $env.PROMPT_COMMAND_RIGHT = ""
        $env.PROMPT_INDICATOR = ""
        $env.PROMPT_MULTILINE_INDICATOR = "::: "

        # --- 5. DIRENV HOOK ---
        $env.config.hooks.env_change.PWD = $env.config.hooks.env_change.PWD? | default []
        $env.config.hooks.env_change.PWD ++= [{||
          if (which direnv | is-empty) { return }

          let direnv_out = (direnv export json | from json | default {})
          if ($direnv_out | is-empty) { return }
          
          load-env $direnv_out

          # In Nu 0.111, we must ensure PATH remains a list if direnv stringified it
          if "PATH" in $env and ($env.PATH | describe) == "string" {
            $env.PATH = ($env.PATH | split row (char env_sep) | path expand --no-symlink)
          }
        }]
      '';
    };
  };
}
